language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install -e .
before_script:
    - pip install -r test_requirements.pip
script:
    - py.test configuration --strict --cov=configuration --cov-report=term-missing --pep8
after_success:
  - coveralls
